name: IslandFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.0
description: Plugin for the IslandFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, BarAPI, CoreProtect]
authors: [Madgeek1450, DarthSalamon, Camzie99, RobinGall2910, PieGuy7896, RedTheDragon_, Alex33856]

# plugin.yml is no longer used to define commands.
